"""Справочник крупных городов для автоподбора климатических и нагрузочных параметров.

Важно:
- модуль предназначен для демонстрационной ВКР-версии;
- значения сгруппированы по крупным городам и региональным климатическим шаблонам;
- для реального проектирования параметры должны уточняться по конкретной площадке
  строительства и действующим нормативным картам СП 20 и СП 131.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, List


@dataclass(frozen=True)
class CityProfile:
    name: str
    wind_region: str
    snow_region: str
    terrain_type: str
    ambient_temp_min_c: float
    ambient_temp_max_c: float
    climate_note: str


_TEMPLATE_DATA = {
    "central": {
        "wind_region": "II",
        "snow_region": "III",
        "terrain_type": "B",
        "ambient_temp_min_c": -28.0,
        "ambient_temp_max_c": 30.0,
        "climate_note": "центральная и средняя полоса",
    },
    "moscow_dense": {
        "wind_region": "II",
        "snow_region": "III",
        "terrain_type": "C",
        "ambient_temp_min_c": -26.0,
        "ambient_temp_max_c": 30.0,
        "climate_note": "крупная плотная городская застройка",
    },
    "northwest": {
        "wind_region": "II",
        "snow_region": "IV",
        "terrain_type": "B",
        "ambient_temp_min_c": -26.0,
        "ambient_temp_max_c": 27.0,
        "climate_note": "северо-западный умеренно влажный климат",
    },
    "north": {
        "wind_region": "III",
        "snow_region": "V",
        "terrain_type": "B",
        "ambient_temp_min_c": -35.0,
        "ambient_temp_max_c": 24.0,
        "climate_note": "северные районы европейской части",
    },
    "arctic": {
        "wind_region": "VI",
        "snow_region": "V",
        "terrain_type": "B",
        "ambient_temp_min_c": -42.0,
        "ambient_temp_max_c": 20.0,
        "climate_note": "северные и заполярные районы",
    },
    "south": {
        "wind_region": "III",
        "snow_region": "II",
        "terrain_type": "B",
        "ambient_temp_min_c": -18.0,
        "ambient_temp_max_c": 34.0,
        "climate_note": "юг европейской части",
    },
    "caucasus": {
        "wind_region": "III",
        "snow_region": "I",
        "terrain_type": "B",
        "ambient_temp_min_c": -14.0,
        "ambient_temp_max_c": 33.0,
        "climate_note": "северный Кавказ и предгорья",
    },
    "lower_volga": {
        "wind_region": "III",
        "snow_region": "II",
        "terrain_type": "B",
        "ambient_temp_min_c": -24.0,
        "ambient_temp_max_c": 33.0,
        "climate_note": "нижнее Поволжье",
    },
    "volga": {
        "wind_region": "II",
        "snow_region": "IV",
        "terrain_type": "B",
        "ambient_temp_min_c": -30.0,
        "ambient_temp_max_c": 31.0,
        "climate_note": "Поволжье и Предуралье",
    },
    "ural": {
        "wind_region": "III",
        "snow_region": "III",
        "terrain_type": "B",
        "ambient_temp_min_c": -34.0,
        "ambient_temp_max_c": 31.0,
        "climate_note": "Урал",
    },
    "west_siberia": {
        "wind_region": "III",
        "snow_region": "IV",
        "terrain_type": "B",
        "ambient_temp_min_c": -38.0,
        "ambient_temp_max_c": 32.0,
        "climate_note": "Западная Сибирь",
    },
    "east_siberia": {
        "wind_region": "III",
        "snow_region": "V",
        "terrain_type": "B",
        "ambient_temp_min_c": -42.0,
        "ambient_temp_max_c": 31.0,
        "climate_note": "Восточная Сибирь",
    },
    "yakutia": {
        "wind_region": "II",
        "snow_region": "I",
        "terrain_type": "B",
        "ambient_temp_min_c": -52.0,
        "ambient_temp_max_c": 30.0,
        "climate_note": "резкоконтинентальный климат Якутии",
    },
    "far_east_coast": {
        "wind_region": "IV",
        "snow_region": "II",
        "terrain_type": "B",
        "ambient_temp_min_c": -24.0,
        "ambient_temp_max_c": 28.0,
        "climate_note": "приморский морской климат",
    },
    "far_east_cont": {
        "wind_region": "III",
        "snow_region": "II",
        "terrain_type": "B",
        "ambient_temp_min_c": -34.0,
        "ambient_temp_max_c": 31.0,
        "climate_note": "континентальный климат Дальнего Востока",
    },
    "sakhalin": {
        "wind_region": "VI",
        "snow_region": "III",
        "terrain_type": "B",
        "ambient_temp_min_c": -28.0,
        "ambient_temp_max_c": 24.0,
        "climate_note": "островной климат Сахалина",
    },
    "kamchatka": {
        "wind_region": "VII",
        "snow_region": "VIII",
        "terrain_type": "B",
        "ambient_temp_min_c": -24.0,
        "ambient_temp_max_c": 22.0,
        "climate_note": "океанический климат Камчатки",
    },
}

_CITY_TO_TEMPLATE = {
    # Города федерального значения и крупнейшие центры
    "Москва": "moscow_dense",
    "Санкт-Петербург": "moscow_dense",
    "Новосибирск": "west_siberia",
    "Екатеринбург": "ural",
    "Казань": "volga",
    "Красноярск": "east_siberia",
    "Нижний Новгород": "volga",
    "Челябинск": "ural",
    "Уфа": "volga",
    "Краснодар": "south",
    "Самара": "volga",
    "Ростов-на-Дону": "south",
    "Омск": "west_siberia",
    "Воронеж": "central",
    "Пермь": "ural",
    "Волгоград": "lower_volga",
    "Саратов": "lower_volga",
    "Тюмень": "ural",
    "Тольятти": "volga",
    "Махачкала": "caucasus",
    "Барнаул": "west_siberia",
    "Ижевск": "volga",
    "Хабаровск": "far_east_cont",
    "Ульяновск": "volga",
    "Иркутск": "east_siberia",
    "Владивосток": "far_east_coast",
    "Ярославль": "central",
    "Ставрополь": "south",
    "Набережные Челны": "volga",
    "Томск": "west_siberia",
    "Балашиха": "moscow_dense",
    "Кемерово": "west_siberia",
    "Оренбург": "volga",
    "Новокузнецк": "west_siberia",
    "Рязань": "central",
    "Чебоксары": "volga",
    "Калининград": "northwest",
    "Пенза": "volga",
    "Липецк": "central",
    "Киров": "volga",
    "Астрахань": "lower_volga",
    "Тула": "central",
    "Сочи": "south",
    "Улан-Удэ": "east_siberia",
    "Курск": "central",
    "Сургут": "west_siberia",
    "Тверь": "central",
    "Магнитогорск": "ural",
    "Грозный": "caucasus",
    "Якутск": "yakutia",
    "Брянск": "central",
    "Иваново": "central",
    "Владимир": "central",
    "Чита": "east_siberia",
    "Нижний Тагил": "ural",
    "Калуга": "central",
    "Белгород": "central",
    "Подольск": "moscow_dense",
    "Волжский": "lower_volga",
    "Вологда": "northwest",
    "Смоленск": "central",
    "Саранск": "volga",
    "Курган": "ural",
    "Череповец": "northwest",
    "Архангельск": "north",
    "Владикавказ": "caucasus",
    "Нижневартовск": "west_siberia",
    "Йошкар-Ола": "volga",
    "Мытищи": "moscow_dense",
    "Стерлитамак": "volga",
    "Кострома": "central",
    "Орёл": "central",
    "Новороссийск": "south",
    "Петрозаводск": "northwest",
    "Братск": "east_siberia",
    "Дзержинск": "volga",
    "Нальчик": "caucasus",
    "Шахты": "south",
    "Орск": "volga",
    "Ангарск": "east_siberia",
    "Благовещенск": "far_east_cont",
    "Дзержинск": "volga",
    "Сыктывкар": "north",
    "Псков": "northwest",
    "Бийск": "west_siberia",
    "Великий Новгород": "northwest",
    "Прокопьевск": "west_siberia",
    "Химки": "moscow_dense",
    "Рыбинск": "central",
    "Балаково": "lower_volga",
    "Южно-Сахалинск": "sakhalin",
    "Армавир": "south",
    "Королёв": "moscow_dense",
    "Люберцы": "moscow_dense",
    "Мурманск": "arctic",
    "Северодвинск": "north",
    "Абакан": "east_siberia",
    "Энгельс": "lower_volga",
    "Волгодонск": "south",
    "Сызрань": "volga",
    "Нефтекамск": "volga",
    "Каменск-Уральский": "ural",
    "Нефтеюганск": "west_siberia",
    "Новочеркасск": "south",
    "Златоуст": "ural",
    "Альметьевск": "volga",
    "Хасавюрт": "caucasus",
    "Керчь": "south",
    "Новый Уренгой": "arctic",
    "Миасс": "ural",
    "Копейск": "ural",
    "Пятигорск": "caucasus",
    "Березники": "ural",
    "Коломна": "moscow_dense",
    "Майкоп": "caucasus",
    "Одинцово": "moscow_dense",
    "Рубцовск": "west_siberia",
    "Домодедово": "moscow_dense",
    "Каспийск": "caucasus",
    "Кисловодск": "caucasus",
    "Салават": "volga",
    "Электросталь": "moscow_dense",
    "Ковров": "central",
    "Петропавловск-Камчатский": "kamchatka",
    "Назрань": "caucasus",
    "Новочебоксарск": "volga",
    "Щёлково": "moscow_dense",
    "Серпухов": "moscow_dense",
    "Дербент": "caucasus",
    "Октябрьский": "volga",
    "Невинномысск": "caucasus",
    "Пушкино": "moscow_dense",
    "Орехово-Зуево": "moscow_dense",
    "Димитровград": "volga",
    "Ессентуки": "caucasus",
    "Кызыл": "east_siberia",
    "Обнинск": "central",
    "Раменское": "moscow_dense",
    "Черкесск": "caucasus",
    "Жуковский": "moscow_dense",
    "Долгопрудный": "moscow_dense",
    "Ногинск": "moscow_dense",
    "Реутов": "moscow_dense",
    "Батайск": "south",
    "Новошахтинск": "south",
    "Новоалтайск": "west_siberia",
    "Первоуральск": "ural",
    "Находка": "far_east_coast",
    "Уссурийск": "far_east_coast",
    "Артём": "far_east_coast",
    "Железногорск": "east_siberia",
    "Ханты-Мансийск": "west_siberia",
    "Евпатория": "south",
    "Симферополь": "south",
    "Севастополь": "south",
    "Михайловск": "caucasus",
    "Видное": "moscow_dense",
    "Таганрог": "south",
    "Камышин": "lower_volga",
    "Ачинск": "east_siberia",
    "Норильск": "arctic",
}


CITY_PROFILES: Dict[str, CityProfile] = {}
for city_name, template_name in _CITY_TO_TEMPLATE.items():
    template = _TEMPLATE_DATA[template_name]
    CITY_PROFILES[city_name] = CityProfile(name=city_name, **template)


def get_city_names() -> List[str]:
    return sorted(CITY_PROFILES.keys())


def get_city_profile(city_name: str) -> CityProfile:
    try:
        return CITY_PROFILES[city_name]
    except KeyError as exc:
        raise KeyError(f"Город '{city_name}' отсутствует во встроенном справочнике.") from exc
